
# Spring Boot server port
server.port=8081

# Enable H2 console for debugging (optional)
spring.h2.console.enabled=true

# Prevent JPA from trying to auto-create/validate schema (we use schema.sql / JDBC)
spring.jpa.hibernate.ddl-auto=none
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration, org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

# Camunda BPM configuration
camunda.bpm.database.type=h2
camunda.bpm.database.schema-update=true

